#!/usr/bin/env bash
# ============================================================
# gituser installer
# Usage: ./install.sh [--dry-run]
#
# What it does:
#   1. Detect OS → determine shell RC file (.zshrc / .bashrc)
#   2. Inject gituser source block into RC file (idempotent)
#   3. Initialize Git user account config file
# ============================================================

set -e

GITUSER_REPO="https://github.com/isac7722/gituser.git"
GITUSER_DEFAULT_DIR="$HOME/.gituser"

# When invoked via curl | bash or bash <(curl ...):
# BASH_SOURCE[0] is empty or not the actual install.sh — treat as remote mode
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"

if [[ -z "$DOTFILES_DIR" || ! -f "$DOTFILES_DIR/install.sh" ]]; then
  echo ""
  echo "╔══════════════════════════════════════╗"
  echo "║       gituser Remote Install          ║"
  echo "╚══════════════════════════════════════╝"
  echo ""

  if [[ -d "$GITUSER_DEFAULT_DIR/.git" ]]; then
    echo "  Existing gituser found: $GITUSER_DEFAULT_DIR"
    echo "  Updating to latest version..."
    git -C "$GITUSER_DEFAULT_DIR" pull --ff-only
  else
    echo "  Cloning repository: $GITUSER_REPO"
    git clone "$GITUSER_REPO" "$GITUSER_DEFAULT_DIR"
  fi

  echo ""
  exec bash "$GITUSER_DEFAULT_DIR/install.sh" "$@"
fi

DRY_RUN=false

# ── Option parsing ──────────────────────────────────────────

for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
  esac
done

# ── Utility functions ───────────────────────────────────────

log()     { echo "  $1"; }
success() { echo "✔  $1"; }
warn()    { echo "⚠  $1"; }
error()   { echo "✗  $1"; exit 1; }
section() { echo ""; echo "── $1 ──────────────────────────────"; }

# ── Start ───────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════╗"
echo "║       gituser Installer               ║"
echo "╚══════════════════════════════════════╝"
$DRY_RUN && warn "DRY-RUN mode: no changes will be made"

# ── 1. Detect OS ────────────────────────────────────────────

section "Detecting OS"

case "$(uname -s)" in
  Darwin*)
    OS="macOS"
    RC_FILE="$HOME/.zshrc"
    ;;
  Linux*)
    OS="Linux"
    RC_FILE="$HOME/.bashrc"
    ;;
  *)
    error "Unsupported OS: $(uname -s)"
    ;;
esac

success "Detected OS: $OS → RC file: $RC_FILE"

# ── 2. Inject source block into RC file ─────────────────────

section "Shell integration ($RC_FILE)"

MARKER_START="# >>> gituser >>>"
MARKER_END="# <<< gituser <<<"

# Determine file extension to load based on OS
# macOS (zsh): loads *.zsh  /  Linux (bash): loads *.bash
if [[ "$OS" == "macOS" ]]; then
  DF_PATTERN="*.zsh"
else
  DF_PATTERN="*.bash"
fi

# Source block content to be inserted into RC file
SOURCE_BLOCK="
$MARKER_START
# gituser auto-load (generated by install.sh)
DOTFILES_DIR=\"$DOTFILES_DIR\"
for _df_file in \"\$DOTFILES_DIR\"/$DF_PATTERN; do
  [ -f \"\$_df_file\" ] && source \"\$_df_file\"
done
unset _df_file
$MARKER_END"

if grep -q "$MARKER_START" "$RC_FILE" 2>/dev/null; then
  success "Already integrated: $RC_FILE"
else
  if $DRY_RUN; then
    log "[dry-run] Source block will be added to $RC_FILE"
    log "[dry-run] Block contents:"
    echo "$SOURCE_BLOCK" | sed 's/^/    /'
  else
    # Create RC file if it doesn't exist
    touch "$RC_FILE"
    printf '%s\n' "$SOURCE_BLOCK" >> "$RC_FILE"
    success "Source block added: $RC_FILE"
  fi
fi

# ── 3. Initialize Git user config file ──────────────────────

section "Git User Config File"

GITUSER_CONFIG_DIR="$HOME/.config/gituser"
GITUSER_CONFIG="$GITUSER_CONFIG_DIR/accounts"
GITUSER_EXAMPLE="$DOTFILES_DIR/config/gitusers.example"

if [[ ! -f "$GITUSER_CONFIG" ]]; then
  if $DRY_RUN; then
    log "[dry-run] Will create $GITUSER_CONFIG"
    log "[dry-run] Template: $GITUSER_EXAMPLE"
  else
    mkdir -p "$GITUSER_CONFIG_DIR"
    cp "$GITUSER_EXAMPLE" "$GITUSER_CONFIG"
    success "Config file created: $GITUSER_CONFIG"
    echo ""
    log "▶ Edit the file below to register your accounts:"
    log "     \$EDITOR $GITUSER_CONFIG"
    log ""
    log "  Format:  aliases:name:email:~/.ssh/key_name"
    log "  Example: work,w:John:john@company.com:~/.ssh/work_ed25519"
  fi
else
  success "Config file already exists: $GITUSER_CONFIG"
fi

# ── Done ────────────────────────────────────────────────────

echo ""
echo "╔══════════════════════════════════════╗"
echo "║       Installation Complete!          ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "  Apply changes immediately:"
echo "    source $RC_FILE"
echo ""
echo "  Switch Git accounts:"
echo "    gituser list      # list accounts"
echo "    gituser <alias>   # switch account"
echo ""
